//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSupplierModel.MulticellBufferService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MulticellBufferService.IMultiCellBufferService")]
    public interface IMultiCellBufferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiCellBufferService/setOneCell", ReplyAction="http://tempuri.org/IMultiCellBufferService/setOneCellResponse")]
        void setOneCell(string encodedOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiCellBufferService/getOneCell", ReplyAction="http://tempuri.org/IMultiCellBufferService/getOneCellResponse")]
        string getOneCell();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMultiCellBufferServiceChannel : HotelSupplierModel.MulticellBufferService.IMultiCellBufferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MultiCellBufferServiceClient : System.ServiceModel.ClientBase<HotelSupplierModel.MulticellBufferService.IMultiCellBufferService>, HotelSupplierModel.MulticellBufferService.IMultiCellBufferService {
        
        public MultiCellBufferServiceClient() {
        }
        
        public MultiCellBufferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MultiCellBufferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiCellBufferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MultiCellBufferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void setOneCell(string encodedOrder) {
            base.Channel.setOneCell(encodedOrder);
        }
        
        public string getOneCell() {
            return base.Channel.getOneCell();
        }
    }
}
